### ISSUE TITLE
WebUI About

### ISSUE THREAD

**Issue by nagyrobi** [dzurikmiroslav/esp32-evse#102]
In WebUI About screen I see these parameters listed incorrectly:

- Proximity pilot	Yes
- Socket lock	Yes
- Residual current monitor	Yes
- Three phase energy meter	Yes
- Energy meter	Current and voltage

Despite not having enabled the "Socket outlet", the "Residual current monitor" and "Three phases" options in the settings. I assume in this case they should be "No" on About page.  "Energy meter" lists "Current and voltage" despite being Dummy or Current sensing only

**Comment by dzurikmiroslav** [comment]
The parameters in this table are not actual settings but HW capabilities.

**Comment by nagyrobi** [comment]
But how can these be set? For example
- i didn't install the pp components at all on the board
- no RCM module plugged in

Thus these are missing hw capabilities. In the settings, these corresponding checkboxes lead to think that the user adjusts the firmware to the hw capabilities, so it would be logic to reflect them in the about screen.

**Comment by dzurikmiroslav** [comment]
It's configured thought board.yaml

**Comment by nagyrobi** [comment]
Ok, so if I remove these, will it be correct?

```yaml
proximity:
  adcChannel: 2
  levels: [1650, 820, 430]

socketLock:
  aGpio: 20
  bGpio: 19
  detectionGpio: 34
  detectionDelay: 1000
  minBreakTime: 1000
```
