### ISSUE TITLE
Pilot/Session auto-stop option

### ISSUE THREAD

**Issue by nagyrobi** [dzurikmiroslav/esp32-evse#113]
I noticed that after charging finishes (not by session limits, but by car), the state returns to B2. For certain car models, this keeps the plug locked to the car. To release it, I need to manually press the disable charging switch on EVSE or on the car, or in the car app. After that it goes to B1, lock releases the plug and I can remove from the car socket (pilot stops, I guess?)

It would be nice to have a "Pilot (or Session) auto-stop" feature in the settings, which when enabled, would automatically switch back to a B1-like state when previous state before B2 was Cx (or Dx?), so the plug can be removed after charging finished, without any additional manual intervention.

Could use a third B state (like B0 or B3 or B1a or B1.5 etc) so we could differentiate from the others to show on HMI to the user in a friendly manner (I'd put a text "Charging finished, plug released").

This would of course mean that car can't go back by itself anymore to C; so if the car wants to pause charging this way and resume later, won't succeed. This should mean one has to remove the plug and re-insert to go through state A again, to start a new session. This is the reason why this feature should be an optional setting through the web ui/nextion.

Session should also be stopped automatically when in this B3 state.

**Comment by nagyrobi** [comment]
The new optional B3 state:

![Image](https://github.com/user-attachments/assets/31527fbf-8ddc-40e8-8779-53ad8e04e127)

**Comment by nagyrobi** [comment]
A trick that can be used on the [ESPHome HMI](https://github.com/nagyrobi/esp32-evse_esphome-lvgl) - every morning at 6:30 it checks if charging is completed by looking at the state being B1 or B2, if it is, disables charging by itself, so you can just remove the plug:

```yaml
time:
  - platform: ...
    on_time:
      - seconds: 0
        minutes: 30
        hours: 6
        then:
          - if:
              condition:
                lambda: |-
                  std::string state = id(evse_state).state;
                  return state == "B1" || state == "B2";
              then:
                - uart.write: !lambda |-
                    return std::vector<uint8_t>({'e','n',' ','0', 0xFF, 0xFF, 0xFF});
                - delay: 5s
                - text_sensor.template.publish:
                    id: evse_charging_statusmsg
                    state: "Charge completed, please unplug"
```
