### ISSUE TITLE
433MHz open charging port

### ISSUE THREAD

**Issue by dzurikmiroslav** [dzurikmiroslav/esp32-evse#93]
Add support 433MHz transmitter to open charging port on some EV cars

**Comment by nagyrobi** [comment]
References for Teslas:
https://github.com/Algafix/pico-tesla-charging-port-opener
https://github.com/stefan73/BetterTeslaChargeportOpener
https://github.com/Robbbbbbbbb/tesla-chargeport
https://github.com/UberGuidoZ/Flipper/tree/main/Sub-GHz/Vehicles/Tesla

In the [ESPHome HMI](https://github.com/nagyrobi/esp32-evse_esphome-lvgl), this works like this:

```yaml
remote_transmitter:
  pin: GPIOXX
  carrier_duty_percent: 100%
  non_blocking: true

button:
  - platform: template
    name: Charge port open via RF
    on_press:
      - remote_transmitter.transmit_raw:
          repeat:
            times: 10
            wait_time: 5ms
          code: [400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -400, 400, -1200, 400, -400, 400, -400, 800, -800, 400, -400, 800, -800, 800, -800, 400, -400, 800, -800, 800, -800, 800, -800, 800, -800, 800, -800, 400, -400, 800, -400, 400, -800, 800, -400, 400, -800, 400, -400, 800, -400, 400, -400, 400, -800, 400, -400, 400, -400, 800, -400, 400, -800, 800, -400, 400, -800, 800, -800, 400, -400, 400, -400, 400, -400, 800, -400, 400, -800, 400, -400, 800]
```

Using a 433.92 MHz transmitter for Europe (I guess it's 315 MHz for USA). STX882 (recommended), or FS1000A (some say it's weaker, but works just fine for me).
